#!/usr/bin/env python3
"""
Impact Slide Builder / Validator - Step 4

Takes Final_Slide_Content.json plus brand_style_summary.json and generates:
- validation_report.json / validation_report.md
- updated_presentation.pptx (optional)
- standalone presentation.html with embedded assets (optional)
- presentation.pdf from HTML via Playwright (optional)

The HTML output follows the frontend-slides fixed-stage architecture:
- 1920x1080 fixed slide canvas
- stage scales uniformly to viewport
- .active / .visible slide switching
- inline CSS/JS
- embedded assets as data URIs
- no inline editing controls

Usage:
  python step4_builder_validator.py --input Final_Slide_Content.json --brand brand_style_summary.json --output out --pptx --html

If neither --pptx nor --html is supplied, both are generated by default.
"""

from __future__ import annotations

import argparse
import base64
import datetime as dt
import html
import json
import math
import mimetypes
import os
import re
import shutil
import subprocess
import sys
import traceback
import webbrowser
from collections import Counter
from pathlib import Path
from string import Template
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

# ----------------------------- optional imports -----------------------------

IMPORT_WARNINGS: Dict[str, str] = {}

try:
    from pptx import Presentation  # type: ignore
    from pptx.dml.color import RGBColor  # type: ignore
    from pptx.enum.shapes import MSO_SHAPE  # type: ignore
    from pptx.enum.text import MSO_AUTO_SIZE, PP_ALIGN  # type: ignore
    from pptx.util import Inches, Pt  # type: ignore
except Exception as exc:  # noqa: BLE001
    IMPORT_WARNINGS["python-pptx"] = str(exc)
    Presentation = None
    RGBColor = None
    MSO_SHAPE = None
    MSO_AUTO_SIZE = None
    PP_ALIGN = None
    Inches = None
    Pt = None

try:
    from PIL import Image  # type: ignore
except Exception as exc:  # noqa: BLE001
    IMPORT_WARNINGS["pillow"] = str(exc)
    Image = None

try:
    from bs4 import BeautifulSoup  # type: ignore
except Exception as exc:  # noqa: BLE001
    IMPORT_WARNINGS["beautifulsoup4"] = str(exc)
    BeautifulSoup = None


# ----------------------------- constants -----------------------------

STAGE_W = 1920
STAGE_H = 1080

# Full viewport-base.css from frontend-slides, embedded so this script is self-contained.
VIEWPORT_BASE_CSS = r"""
/* ===========================================
   FIXED 16:9 STAGE: MANDATORY BASE STYLES
   Include this ENTIRE file in every presentation.
   Slides are authored at 1920×1080 and scaled as a whole.
   =========================================== */

/* 1. Lock the browser viewport */
html,
body {
    width: 100%;
    height: 100%;
    margin: 0;
    overflow: hidden;
    background: var(--stage-bg, #000);
}

/* 2. Full-window deck viewport */
.deck-viewport {
    position: fixed;
    inset: 0;
    overflow: hidden;
    background: var(--stage-bg, #000);
}

/* 3. Fixed 16:9 design canvas.
   JavaScript sets transform: translate(...) scale(...). */
.deck-stage {
    position: absolute;
    left: 0;
    top: 0;
    width: 1920px;
    height: 1080px;
    overflow: hidden;
    transform-origin: 0 0;
    background: var(--slide-bg, #fff);
}

/* 4. Slides stack inside the fixed stage.
   Content must be laid out at 1920×1080, not reflowed per device. */
.slide {
    position: absolute;
    inset: 0;
    width: 1920px;
    height: 1080px;
    overflow: hidden;
    display: block;
    visibility: hidden;
    opacity: 0;
    pointer-events: none;
    background: var(--slide-bg, #fff);
}

.slide.active,
.slide.visible {
    visibility: visible;
    opacity: 1;
    pointer-events: auto;
    z-index: 1;
}

/* 5. Keep media inside authored slide bounds */
img,
video,
canvas,
svg {
    max-width: 100%;
    max-height: 100%;
}

/* 6. Presentation chrome stays outside the slide design system */
.deck-controls {
    position: fixed;
    left: 50%;
    bottom: 22px;
    transform: translateX(-50%);
    z-index: 1000;
}

/* 7. Print one fixed-size slide per page */
@media print {
    html,
    body {
        width: 1920px;
        height: auto;
        overflow: visible;
        background: #fff;
    }

    .deck-viewport {
        position: static;
        overflow: visible;
        background: #fff;
    }

    .deck-stage {
        position: static;
        width: auto;
        height: auto;
        transform: none !important;
        background: none;
    }

    .slide {
        position: relative;
        display: block !important;
        visibility: visible !important;
        opacity: 1 !important;
        pointer-events: auto !important;
        width: 1920px;
        height: 1080px;
        break-after: page;
        page-break-after: always;
    }

    .slide:last-child {
        break-after: auto;
        page-break-after: auto;
    }

    .deck-controls {
        display: none !important;
    }
}

/* 8. Reduced motion */
@media (prefers-reduced-motion: reduce) {
    *,
    *::before,
    *::after {
        animation-duration: 0.01ms !important;
        transition-duration: 0.2s !important;
    }
}
"""


# ----------------------------- general helpers -----------------------------


def now_iso() -> str:
    return dt.datetime.now().replace(microsecond=0).isoformat()


def default_output_dir(input_json: Path) -> Path:
    stamp = dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    return input_json.parent / f"ImpactSlide_Step4_Output_{stamp}"


def clean_text(value: Any) -> str:
    if value is None:
        return ""
    text = str(value).replace("\x00", " ")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def slugify(value: str, fallback: str = "item") -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", clean_text(value).lower()).strip("-")
    return slug or fallback


def words(text: str) -> List[str]:
    return re.findall(r"\b[\w'-]+\b", clean_text(text))


def load_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        # Optional recovery if json_repair is available.
        try:
            from json_repair import repair_json  # type: ignore

            return json.loads(repair_json(path.read_text(encoding="utf-8")))
        except Exception:
            raise


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False, default=json_default), encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def json_default(obj: Any) -> Any:
    if isinstance(obj, (dt.datetime, dt.date)):
        return obj.isoformat()
    if isinstance(obj, Path):
        return str(obj)
    return str(obj)


def as_list(value: Any) -> List[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    return [value]


def html_escape(value: Any) -> str:
    return html.escape(clean_text(value), quote=True)


def shorten(value: Any, max_chars: int = 160) -> str:
    text = clean_text(value)
    if len(text) <= max_chars:
        return text
    return text[: max_chars - 1].rstrip() + "…"


def parse_hex_color(value: Any) -> Optional[str]:
    if value is None:
        return None
    text = clean_text(value).upper()
    m = re.search(r"#[0-9A-F]{6}\b", text)
    if m:
        return m.group(0)
    # Accept bare RGB hex from python-pptx color extraction.
    m = re.fullmatch(r"[0-9A-F]{6}", text)
    if m:
        return "#" + text
    return None


def hex_to_rgb_tuple(value: str) -> Tuple[int, int, int]:
    value = parse_hex_color(value) or "#000000"
    return int(value[1:3], 16), int(value[3:5], 16), int(value[5:7], 16)


def luminance(hex_color: str) -> float:
    r, g, b = [x / 255 for x in hex_to_rgb_tuple(hex_color)]

    def channel(c: float) -> float:
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4

    return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b)


def contrast_ratio(color_a: str, color_b: str) -> float:
    l1 = luminance(color_a)
    l2 = luminance(color_b)
    lighter, darker = max(l1, l2), min(l1, l2)
    return round((lighter + 0.05) / (darker + 0.05), 2)


def is_neutral_color(hex_color: str) -> bool:
    r, g, b = hex_to_rgb_tuple(hex_color)
    max_delta = max(abs(r - g), abs(g - b), abs(r - b))
    avg = (r + g + b) / 3
    return max_delta < 18 or avg < 24 or avg > 235


def choose_text_color(bg: str) -> str:
    return "#FFFFFF" if luminance(bg) < 0.42 else "#111827"


def lighten(hex_color: str, factor: float = 0.88) -> str:
    r, g, b = hex_to_rgb_tuple(hex_color)
    r = int(r + (255 - r) * factor)
    g = int(g + (255 - g) * factor)
    b = int(b + (255 - b) * factor)
    return f"#{r:02X}{g:02X}{b:02X}"


def darken(hex_color: str, factor: float = 0.2) -> str:
    r, g, b = hex_to_rgb_tuple(hex_color)
    r = int(r * (1 - factor))
    g = int(g * (1 - factor))
    b = int(b * (1 - factor))
    return f"#{r:02X}{g:02X}{b:02X}"


def rgbcolor(hex_color: str) -> Any:
    r, g, b = hex_to_rgb_tuple(hex_color)
    if RGBColor is None:
        return None
    return RGBColor(r, g, b)


def file_to_data_uri(path: Path, max_image_dim: int = 1800, quality: int = 86) -> Optional[str]:
    if not path.exists() or not path.is_file():
        return None
    mime = mimetypes.guess_type(str(path))[0] or "application/octet-stream"
    data = path.read_bytes()
    # Resize very large raster images before embedding to keep HTML manageable.
    if Image is not None and mime.startswith("image/") and path.suffix.lower() not in {".svg", ".gif"}:
        try:
            with Image.open(path) as img:
                if max(img.size) > max_image_dim:
                    img = img.convert("RGB") if img.mode not in {"RGB", "RGBA"} else img.copy()
                    img.thumbnail((max_image_dim, max_image_dim), Image.LANCZOS)
                    import io

                    buf = io.BytesIO()
                    fmt = "PNG" if img.mode == "RGBA" else "JPEG"
                    mime = "image/png" if fmt == "PNG" else "image/jpeg"
                    img.save(buf, format=fmt, quality=quality, optimize=True)
                    data = buf.getvalue()
        except Exception:
            pass
    return f"data:{mime};base64," + base64.b64encode(data).decode("ascii")


# ----------------------------- models / normalization -----------------------------


class BuildContext:
    def __init__(self) -> None:
        self.errors: List[str] = []
        self.warnings: List[str] = []
        self.infos: List[str] = []
        self.outputs: Dict[str, Any] = {}
        self.html_validation: Dict[str, Any] = {}
        self.theme: Dict[str, Any] = {}

    def error(self, message: str) -> None:
        self.errors.append(message)

    def warn(self, message: str) -> None:
        self.warnings.append(message)

    def info(self, message: str) -> None:
        self.infos.append(message)


def normalize_final_json(data: Dict[str, Any]) -> Dict[str, Any]:
    """Accept both Final Slide JSON and small variations from GPT output."""
    presentation = data.get("presentation") or data.get("presentation_plan") or {}
    slides = data.get("slides") or data.get("final_slides") or data.get("slide_update_plan") or []
    if not isinstance(slides, list):
        slides = []
    normalized_slides = []
    for idx, slide in enumerate(slides, 1):
        if not isinstance(slide, dict):
            continue
        content = slide.get("content") or {}
        if not isinstance(content, dict):
            content = {"body_text": clean_text(content)}
        visual_spec = slide.get("visual_spec") or {}
        if not isinstance(visual_spec, dict):
            visual_spec = {"overall_layout_description": clean_text(visual_spec)}
        normalized = dict(slide)
        normalized.setdefault("slide_number", idx)
        normalized.setdefault("section", slide.get("section") or "What")
        normalized.setdefault("title", slide.get("proposed_title") or slide.get("title") or f"Slide {idx}")
        normalized.setdefault("purpose", slide.get("new_slide_purpose") or slide.get("purpose") or "")
        normalized.setdefault("audience_takeaway", slide.get("audience_takeaway") or slide.get("key_message") or "")
        normalized.setdefault("layout_type", slide.get("layout_type") or infer_layout_type(slide))
        normalized["content"] = content
        normalized["visual_spec"] = visual_spec
        normalized_slides.append(normalized)
    return {"presentation": presentation, "slides": normalized_slides}


def infer_layout_type(slide: Dict[str, Any]) -> str:
    visual_spec = slide.get("visual_spec") or {}
    primary_visual = visual_spec.get("primary_visual") if isinstance(visual_spec, dict) else {}
    visual_type = clean_text((primary_visual or {}).get("type", "")).lower()
    title = clean_text(slide.get("title") or slide.get("proposed_title") or "").lower()
    content = slide.get("content") or {}
    if slide.get("slide_number") == 1 or "title" in title:
        return "title_or_opening"
    if "process" in visual_type or "flow" in visual_type:
        return "full_process_flow"
    if "timeline" in visual_type or "roadmap" in visual_type:
        return "timeline"
    if "dashboard" in visual_type or content.get("key_stats"):
        return "metric_dashboard"
    if "table" in visual_type or "comparison" in visual_type or "grid" in visual_type:
        return "comparison_grid"
    if "quote" in visual_type:
        return "quote_card"
    return "split_text_visual"


# ----------------------------- validation -----------------------------


def validate_final_content(deck: Dict[str, Any], ctx: BuildContext) -> Dict[str, Any]:
    presentation = deck.get("presentation", {})
    slides = deck.get("slides", [])
    checks: List[Dict[str, Any]] = []

    def add_check(name: str, status: str, notes: str = "") -> None:
        checks.append({"check": name, "status": status, "notes": notes})
        if status == "error":
            ctx.error(f"{name}: {notes}")
        elif status == "warning":
            ctx.warn(f"{name}: {notes}")

    add_check("Presentation object present", "pass" if presentation else "warning", "Missing or empty presentation metadata" if not presentation else "")
    add_check("Slides array present", "pass" if slides else "error", "" if slides else "No slides found")

    title = clean_text(presentation.get("title") or "")
    add_check("Presentation title present", "pass" if title else "warning", "" if title else "Missing presentation.title")

    slide_numbers = []
    for idx, slide in enumerate(slides, 1):
        sn = slide.get("slide_number", idx)
        slide_numbers.append(sn)
        title = clean_text(slide.get("title") or "")
        if not title:
            add_check(f"Slide {idx} title", "warning", "Missing title")
        purpose = clean_text(slide.get("purpose") or "")
        if not purpose:
            add_check(f"Slide {idx} purpose", "warning", "Missing purpose")
        content = slide.get("content") or {}
        bullets = [clean_text(b) for b in as_list(content.get("bullets")) if clean_text(b)]
        if len(bullets) > 5:
            add_check(f"Slide {idx} bullet count", "warning", f"{len(bullets)} bullets; recommended max is 3-5")
        long_bullets = [b for b in bullets if len(words(b)) > 14]
        if long_bullets:
            add_check(f"Slide {idx} bullet length", "warning", f"{len(long_bullets)} bullets exceed ~14 words")
        visual_spec = slide.get("visual_spec") or {}
        if not visual_spec:
            add_check(f"Slide {idx} visual spec", "warning", "Missing visual_spec")
        evidence = collect_slide_evidence_refs(slide)
        if not evidence:
            add_check(f"Slide {idx} evidence", "warning", "No evidence references found")

    duplicates = [num for num, count in Counter(slide_numbers).items() if count > 1]
    add_check("Slide numbers unique", "pass" if not duplicates else "warning", f"Duplicate slide numbers: {duplicates}" if duplicates else "")
    add_check("Slide count consistency", "pass", f"Detected {len(slides)} slides")

    return {"checks": checks, "slide_count": len(slides), "errors": ctx.errors, "warnings": ctx.warnings}


def collect_slide_evidence_refs(slide: Dict[str, Any]) -> List[str]:
    refs: List[str] = []
    for ev in as_list(slide.get("evidence_sources")):
        if isinstance(ev, dict):
            ref = ev.get("evidence_id") or ev.get("source") or ev.get("source_file")
            if ref:
                refs.append(clean_text(ref))
        else:
            refs.append(clean_text(ev))
    content = slide.get("content") or {}
    for stat in as_list(content.get("key_stats")):
        if isinstance(stat, dict) and stat.get("source"):
            refs.append(clean_text(stat.get("source")))
    if slide.get("evidence_to_use"):
        refs.extend(clean_text(x) for x in as_list(slide.get("evidence_to_use")))
    return [r for r in refs if r]


# ----------------------------- brand theme resolver -----------------------------


def resolve_brand_theme(brand: Dict[str, Any], ctx: BuildContext) -> Dict[str, Any]:
    colors = extract_brand_colors(brand)
    fonts = extract_brand_fonts(brand)
    fallbacks_used: List[str] = []

    if colors:
        non_neutral = [c for c in colors if not is_neutral_color(c)]
        accent = non_neutral[0] if non_neutral else colors[0]
        # Choose a light/paper background by default for readability unless deck appears dark-heavy.
        dark_candidates = [c for c in colors if luminance(c) < 0.18]
        light_candidates = [c for c in colors if luminance(c) > 0.82]
        slide_bg = light_candidates[0] if light_candidates else "#F8FAFC"
        stage_bg = dark_candidates[0] if dark_candidates else darken(accent, 0.72)
        text = choose_text_color(slide_bg)
        muted = "#475569" if text == "#111827" else "#CBD5E1"
        panel = "#FFFFFF" if luminance(slide_bg) > 0.72 else lighten(slide_bg, 0.12)
    else:
        fallbacks_used.append("No valid brand colors found; using neutral executive palette")
        accent = "#2563EB"
        slide_bg = "#F8FAFC"
        stage_bg = "#0F172A"
        text = "#111827"
        muted = "#475569"
        panel = "#FFFFFF"

    if contrast_ratio(text, slide_bg) < 4.5:
        text = choose_text_color(slide_bg)
        fallbacks_used.append("Adjusted text color for contrast")
    if contrast_ratio(accent, slide_bg) < 2.2:
        accent = darken(accent, 0.35) if luminance(slide_bg) > 0.6 else lighten(accent, 0.55)
        fallbacks_used.append("Adjusted accent color for visibility")

    display_font = fonts[0] if fonts else "Manrope"
    body_font = fonts[1] if len(fonts) > 1 else display_font
    if not fonts:
        fallbacks_used.append("No brand fonts found; using Manrope")

    theme = {
        "available": bool(brand),
        "colors": {
            "stage_bg": stage_bg,
            "slide_bg": slide_bg,
            "panel_bg": panel,
            "text_primary": text,
            "text_secondary": muted,
            "accent": accent,
            "accent_light": lighten(accent, 0.82),
            "accent_dark": darken(accent, 0.35),
            "border": "#D9E2EC" if text == "#111827" else "rgba(255,255,255,0.18)",
            "brand_palette": colors[:12],
        },
        "fonts": {
            "display": display_font,
            "body": body_font,
            "fallback_stack": "Arial, sans-serif",
            "web_font_link": build_google_font_link(display_font, body_font),
        },
        "layout": {
            "stage_width": STAGE_W,
            "stage_height": STAGE_H,
            "slide_padding": 96,
            "content_gap": 42,
            "corner_radius": 28,
        },
        "fallbacks_used": fallbacks_used,
        "contrast": {
            "text_on_slide_bg": contrast_ratio(text, slide_bg),
            "accent_on_slide_bg": contrast_ratio(accent, slide_bg),
        },
    }
    ctx.theme = theme
    for item in fallbacks_used:
        ctx.warn(item)
    return theme


def extract_brand_colors(brand: Dict[str, Any]) -> List[str]:
    colors: List[str] = []

    def walk(obj: Any) -> None:
        if isinstance(obj, dict):
            for key, value in obj.items():
                if str(key).lower() in {"color", "hex"}:
                    c = parse_hex_color(value)
                    if c:
                        colors.append(c)
                walk(value)
        elif isinstance(obj, list):
            for item in obj:
                walk(item)
        elif isinstance(obj, str):
            for match in re.findall(r"#[0-9a-fA-F]{6}\b", obj):
                colors.append(match.upper())

    walk(brand)
    result = []
    seen = set()
    for c in colors:
        c = c.upper()
        if c not in seen:
            seen.add(c)
            result.append(c)
    # Avoid returning only transparent theme:* pseudo-values; parse_hex_color filters those out.
    return result


def extract_brand_fonts(brand: Dict[str, Any]) -> List[str]:
    font_candidates: List[str] = []

    def add_font(value: Any) -> None:
        text = clean_text(value)
        if not text:
            return
        # Drop obviously non-font text.
        if len(text) > 80 or text.lower().startswith("observed"):
            return
        if text.lower() in {"none", "null", "unknown"}:
            return
        font_candidates.append(text)

    def walk(obj: Any, parent_key: str = "") -> None:
        if isinstance(obj, dict):
            for key, value in obj.items():
                key_l = str(key).lower()
                if key_l in {"font", "font_name", "name"} and "font" in parent_key.lower():
                    add_font(value)
                elif key_l == "font" or "font" in key_l or "typography" in key_l:
                    if isinstance(value, str):
                        # Extract names from comma-separated prose lightly.
                        for part in re.split(r"[,;\n]", value):
                            add_font(part.strip(" .'\"`"))
                    else:
                        walk(value, key_l)
                else:
                    walk(value, key_l)
        elif isinstance(obj, list):
            for item in obj:
                walk(item, parent_key)

    walk(brand)
    cleaned: List[str] = []
    seen = set()
    banned = {"theme", "body", "display", "heading", "headings", "fonts", "typography", "top_fonts"}
    for f in font_candidates:
        f = re.sub(r"\s+", " ", f).strip()
        f = f.split("|")[0].strip()
        if not f or f.lower() in banned or f.startswith("#"):
            continue
        if f.lower() not in seen:
            seen.add(f.lower())
            cleaned.append(f)
    return cleaned[:4]


def build_google_font_link(display_font: str, body_font: str) -> str:
    # Always load robust defaults. If the brand font is a Google font and name matches,
    # this link also covers common cases. Unknown/local brand fonts still work if installed.
    families = {"Manrope:wght@400;500;600;700;800", "Source+Serif+4:wght@400;600;700"}
    common_google = {
        "Archivo Black": "Archivo+Black",
        "Space Grotesk": "Space+Grotesk:wght@400;500;700",
        "Manrope": "Manrope:wght@400;500;600;700;800",
        "Syne": "Syne:wght@400;700;800",
        "Cormorant": "Cormorant:wght@400;600;700",
        "IBM Plex Sans": "IBM+Plex+Sans:wght@300;400;500;700",
        "Bodoni Moda": "Bodoni+Moda:wght@400;700;900",
        "DM Sans": "DM+Sans:wght@400;500;700",
        "Plus Jakarta Sans": "Plus+Jakarta+Sans:wght@400;500;700;800",
        "Outfit": "Outfit:wght@400;500;700;800",
        "Fraunces": "Fraunces:wght@400;700;900",
        "Work Sans": "Work+Sans:wght@400;500;700",
        "JetBrains Mono": "JetBrains+Mono:wght@400;700",
        "Archivo": "Archivo:wght@400;700;800",
        "Nunito": "Nunito:wght@400;700",
        "Lora": "Lora:wght@400;600;700",
        "Jost": "Jost:wght@400;500;700",
    }
    for font in [display_font, body_font]:
        if font in common_google:
            families.add(common_google[font])
    family_query = "&".join(f"family={f}" for f in sorted(families))
    return f"https://fonts.googleapis.com/css2?{family_query}&display=swap"


# ----------------------------- asset resolution -----------------------------


def build_asset_map(asset_manifest: Optional[Any], asset_root: Optional[Path], ctx: BuildContext) -> Dict[str, str]:
    """Return lookup key -> data URI."""
    asset_paths: List[Path] = []
    if asset_manifest:
        entries = asset_manifest if isinstance(asset_manifest, list) else asset_manifest.get("assets", []) if isinstance(asset_manifest, dict) else []
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            for key in ["path", "absolute_path", "file_path"]:
                p = entry.get(key)
                if p and Path(str(p)).exists():
                    asset_paths.append(Path(str(p)))
    if asset_root and asset_root.exists():
        for ext in ["*.png", "*.jpg", "*.jpeg", "*.webp", "*.gif", "*.svg", "*.bmp"]:
            asset_paths.extend(asset_root.rglob(ext))
    result: Dict[str, str] = {}
    seen_paths = set()
    for path in asset_paths:
        try:
            path = path.resolve()
            if path in seen_paths:
                continue
            seen_paths.add(path)
            uri = file_to_data_uri(path)
            if not uri:
                continue
            keys = {path.name.lower(), path.stem.lower(), str(path).lower()}
            for key in keys:
                result[key] = uri
        except Exception as exc:  # noqa: BLE001
            ctx.warn(f"Could not embed asset {path}: {exc}")
    if result:
        ctx.info(f"Embedded {len(seen_paths)} asset(s) for HTML output")
    return result


def find_asset_uri(asset_ref: str, asset_map: Dict[str, str]) -> Optional[str]:
    ref = clean_text(asset_ref).lower()
    if not ref:
        return None
    if ref in asset_map:
        return asset_map[ref]
    basename = Path(ref).name.lower()
    if basename in asset_map:
        return asset_map[basename]
    stem = Path(ref).stem.lower()
    if stem in asset_map:
        return asset_map[stem]
    for key, uri in asset_map.items():
        if basename and basename in key:
            return uri
        if stem and stem in key:
            return uri
    return None


# ----------------------------- PPTX builder -----------------------------


def build_pptx(deck: Dict[str, Any], theme: Dict[str, Any], output_path: Path, ctx: BuildContext) -> Optional[Path]:
    if Presentation is None or Inches is None or Pt is None or MSO_SHAPE is None:
        ctx.error("Cannot build PPTX: python-pptx is not installed or failed to import")
        return None

    prs = Presentation()
    prs.slide_width = Inches(13.333333)
    prs.slide_height = Inches(7.5)
    blank_layout = prs.slide_layouts[6]

    slides = deck.get("slides", [])
    presentation = deck.get("presentation", {})
    for idx, slide_data in enumerate(slides, 1):
        slide = prs.slides.add_slide(blank_layout)
        add_pptx_background(slide, theme)
        if idx == 1 or slide_data.get("layout_type") == "title_or_opening":
            render_pptx_title_slide(slide, slide_data, presentation, theme, idx, len(slides))
        elif slide_data.get("layout_type") == "metric_dashboard":
            render_pptx_metric_slide(slide, slide_data, theme, idx, len(slides))
        elif slide_data.get("layout_type") in {"full_process_flow", "timeline", "roadmap"}:
            render_pptx_process_slide(slide, slide_data, theme, idx, len(slides))
        elif slide_data.get("layout_type") in {"comparison_grid", "data_table"}:
            render_pptx_comparison_slide(slide, slide_data, theme, idx, len(slides))
        else:
            render_pptx_default_slide(slide, slide_data, theme, idx, len(slides))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    prs.save(str(output_path))
    ctx.outputs["pptx"] = str(output_path)
    return output_path


def add_pptx_background(slide: Any, theme: Dict[str, Any]) -> None:
    colors = theme["colors"]
    shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, Inches(13.333333), Inches(7.5))
    shape.fill.solid()
    shape.fill.fore_color.rgb = rgbcolor(colors["slide_bg"])
    shape.line.color.rgb = rgbcolor(colors["slide_bg"])


def pptx_add_textbox(
    slide: Any,
    text: str,
    x: float,
    y: float,
    w: float,
    h: float,
    size: float,
    color: str,
    font: str,
    bold: bool = False,
    align: Optional[Any] = None,
) -> Any:
    shape = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = shape.text_frame
    tf.clear()
    tf.word_wrap = True
    try:
        tf.auto_size = MSO_AUTO_SIZE.TEXT_TO_FIT_SHAPE
    except Exception:
        pass
    p = tf.paragraphs[0]
    p.text = clean_text(text)
    if align is not None:
        p.alignment = align
    p.font.name = font
    p.font.size = Pt(size)
    p.font.bold = bold
    p.font.color.rgb = rgbcolor(color)
    return shape


def pptx_add_bullets(slide: Any, bullets: List[str], x: float, y: float, w: float, h: float, theme: Dict[str, Any], size: float = 19) -> Any:
    colors = theme["colors"]
    font = theme["fonts"]["body"]
    shape = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = shape.text_frame
    tf.clear()
    tf.word_wrap = True
    for idx, bullet in enumerate(bullets[:6]):
        p = tf.paragraphs[0] if idx == 0 else tf.add_paragraph()
        p.text = clean_text(bullet)
        p.level = 0
        p.font.name = font
        p.font.size = Pt(size)
        p.font.color.rgb = rgbcolor(colors["text_primary"])
        p.space_after = Pt(12)
    return shape


def pptx_add_footer(slide: Any, slide_idx: int, total: int, theme: Dict[str, Any]) -> None:
    colors = theme["colors"]
    pptx_add_textbox(
        slide,
        f"{slide_idx:02d} / {total:02d}",
        11.65,
        6.95,
        1.1,
        0.25,
        9,
        colors["text_secondary"],
        theme["fonts"]["body"],
        False,
    )


def add_section_label(slide: Any, section: str, theme: Dict[str, Any]) -> None:
    colors = theme["colors"]
    label = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(0.65), Inches(0.42), Inches(1.3), Inches(0.32))
    label.fill.solid()
    label.fill.fore_color.rgb = rgbcolor(colors["accent_light"])
    label.line.color.rgb = rgbcolor(colors["accent_light"])
    tf = label.text_frame
    tf.clear()
    p = tf.paragraphs[0]
    p.text = clean_text(section).upper()
    p.alignment = PP_ALIGN.CENTER
    p.font.name = theme["fonts"]["body"]
    p.font.size = Pt(8)
    p.font.bold = True
    p.font.color.rgb = rgbcolor(colors["accent_dark"])


def render_pptx_title_slide(slide: Any, slide_data: Dict[str, Any], presentation: Dict[str, Any], theme: Dict[str, Any], idx: int, total: int) -> None:
    colors = theme["colors"]
    title = slide_data.get("title") or presentation.get("title") or "Presentation"
    subtitle = slide_data.get("subtitle") or presentation.get("subtitle") or presentation.get("audience") or ""
    headline = (slide_data.get("content") or {}).get("headline") or slide_data.get("audience_takeaway") or ""
    # Accent block
    block = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0.65), Inches(0.65), Inches(0.22), Inches(6.2))
    block.fill.solid()
    block.fill.fore_color.rgb = rgbcolor(colors["accent"])
    block.line.color.rgb = rgbcolor(colors["accent"])
    pptx_add_textbox(slide, title, 1.05, 1.25, 10.8, 1.4, 38, colors["text_primary"], theme["fonts"]["display"], True)
    if subtitle:
        pptx_add_textbox(slide, subtitle, 1.08, 2.65, 9.8, 0.55, 18, colors["text_secondary"], theme["fonts"]["body"])
    if headline:
        pptx_add_textbox(slide, headline, 1.08, 4.75, 9.7, 0.9, 22, colors["accent_dark"], theme["fonts"]["body"], True)
    pptx_add_footer(slide, idx, total, theme)


def render_pptx_default_slide(slide: Any, slide_data: Dict[str, Any], theme: Dict[str, Any], idx: int, total: int) -> None:
    colors = theme["colors"]
    add_section_label(slide, slide_data.get("section", ""), theme)
    pptx_add_textbox(slide, slide_data.get("title", ""), 0.65, 0.9, 7.3, 0.7, 26, colors["text_primary"], theme["fonts"]["display"], True)
    headline = (slide_data.get("content") or {}).get("headline") or slide_data.get("audience_takeaway") or ""
    if headline:
        pptx_add_textbox(slide, headline, 0.68, 1.72, 6.2, 0.65, 17, colors["accent_dark"], theme["fonts"]["body"], True)
    bullets = [clean_text(b) for b in as_list((slide_data.get("content") or {}).get("bullets")) if clean_text(b)]
    pptx_add_bullets(slide, bullets, 0.8, 2.55, 5.9, 3.5, theme, 18)
    add_visual_placeholder(slide, slide_data, 7.25, 1.45, 5.3, 4.85, theme)
    add_evidence_line(slide, slide_data, 0.75, 6.45, 10.5, theme)
    pptx_add_footer(slide, idx, total, theme)


def render_pptx_metric_slide(slide: Any, slide_data: Dict[str, Any], theme: Dict[str, Any], idx: int, total: int) -> None:
    colors = theme["colors"]
    add_section_label(slide, slide_data.get("section", ""), theme)
    pptx_add_textbox(slide, slide_data.get("title", ""), 0.65, 0.9, 10.2, 0.7, 26, colors["text_primary"], theme["fonts"]["display"], True)
    stats = as_list((slide_data.get("content") or {}).get("key_stats"))
    if not stats:
        bullets = as_list((slide_data.get("content") or {}).get("bullets"))
        stats = [{"label": f"Point {i+1}", "value": clean_text(b)} for i, b in enumerate(bullets[:4])]
    card_w = 2.85
    x0 = 0.8
    for i, stat in enumerate(stats[:4]):
        x = x0 + i * 3.05
        card = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(x), Inches(2.0), Inches(card_w), Inches(2.0))
        card.fill.solid()
        card.fill.fore_color.rgb = rgbcolor(colors["panel_bg"])
        card.line.color.rgb = rgbcolor(colors["border"] if colors["border"].startswith("#") else colors["accent_light"])
        if isinstance(stat, dict):
            value = stat.get("value") or stat.get("label") or ""
            label = stat.get("label") or stat.get("source") or ""
        else:
            value, label = clean_text(stat), ""
        pptx_add_textbox(slide, value, x + 0.22, 2.32, card_w - 0.44, 0.55, 24, colors["accent_dark"], theme["fonts"]["display"], True)
        pptx_add_textbox(slide, label, x + 0.22, 3.05, card_w - 0.44, 0.65, 12, colors["text_secondary"], theme["fonts"]["body"])
    bullets = [clean_text(b) for b in as_list((slide_data.get("content") or {}).get("bullets")) if clean_text(b)]
    if bullets:
        pptx_add_bullets(slide, bullets, 1.0, 4.75, 10.8, 1.3, theme, 16)
    add_evidence_line(slide, slide_data, 0.75, 6.45, 10.5, theme)
    pptx_add_footer(slide, idx, total, theme)


def render_pptx_process_slide(slide: Any, slide_data: Dict[str, Any], theme: Dict[str, Any], idx: int, total: int) -> None:
    colors = theme["colors"]
    add_section_label(slide, slide_data.get("section", ""), theme)
    pptx_add_textbox(slide, slide_data.get("title", ""), 0.65, 0.9, 10.5, 0.7, 26, colors["text_primary"], theme["fonts"]["display"], True)
    steps = extract_visual_steps(slide_data)
    if not steps:
        steps = [clean_text(b) for b in as_list((slide_data.get("content") or {}).get("bullets")) if clean_text(b)]
    steps = steps[:5]
    if not steps:
        steps = ["Step 1", "Step 2", "Step 3"]
    card_w = 11.7 / max(len(steps), 1)
    for i, step in enumerate(steps):
        x = 0.75 + i * card_w
        circ = slide.shapes.add_shape(MSO_SHAPE.OVAL, Inches(x + 0.12), Inches(2.22), Inches(0.52), Inches(0.52))
        circ.fill.solid()
        circ.fill.fore_color.rgb = rgbcolor(colors["accent"])
        circ.line.color.rgb = rgbcolor(colors["accent"])
        pptx_add_textbox(slide, str(i + 1), x + 0.12, 2.32, 0.52, 0.25, 10, choose_text_color(colors["accent"]), theme["fonts"]["body"], True, PP_ALIGN.CENTER)
        if i < len(steps) - 1:
            line = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(x + 0.72), Inches(2.46), Inches(max(card_w - 0.62, 0.4)), Inches(0.035))
            line.fill.solid()
            line.fill.fore_color.rgb = rgbcolor(colors["accent_light"])
            line.line.color.rgb = rgbcolor(colors["accent_light"])
        card = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(x + 0.04), Inches(3.05), Inches(card_w - 0.25), Inches(1.65))
        card.fill.solid()
        card.fill.fore_color.rgb = rgbcolor(colors["panel_bg"])
        card.line.color.rgb = rgbcolor(colors["accent_light"])
        pptx_add_textbox(slide, step, x + 0.18, 3.32, max(card_w - 0.55, 0.7), 0.9, 14, colors["text_primary"], theme["fonts"]["body"], True)
    add_evidence_line(slide, slide_data, 0.75, 6.45, 10.5, theme)
    pptx_add_footer(slide, idx, total, theme)


def render_pptx_comparison_slide(slide: Any, slide_data: Dict[str, Any], theme: Dict[str, Any], idx: int, total: int) -> None:
    colors = theme["colors"]
    add_section_label(slide, slide_data.get("section", ""), theme)
    pptx_add_textbox(slide, slide_data.get("title", ""), 0.65, 0.9, 10.5, 0.7, 26, colors["text_primary"], theme["fonts"]["display"], True)
    bullets = [clean_text(b) for b in as_list((slide_data.get("content") or {}).get("bullets")) if clean_text(b)]
    steps = extract_visual_steps(slide_data) or bullets
    cards = steps[:4] if steps else ["Point 1", "Point 2", "Point 3"]
    cols = 2 if len(cards) > 2 else len(cards)
    rows = math.ceil(len(cards) / max(cols, 1))
    for i, item in enumerate(cards):
        col = i % cols
        row = i // cols
        x = 0.85 + col * 6.1
        y = 2.0 + row * 1.95
        card = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(x), Inches(y), Inches(5.45), Inches(1.45))
        card.fill.solid()
        card.fill.fore_color.rgb = rgbcolor(colors["panel_bg"])
        card.line.color.rgb = rgbcolor(colors["accent_light"])
        pptx_add_textbox(slide, item, x + 0.25, y + 0.25, 4.85, 0.78, 15, colors["text_primary"], theme["fonts"]["body"], True)
    add_evidence_line(slide, slide_data, 0.75, 6.45, 10.5, theme)
    pptx_add_footer(slide, idx, total, theme)


def add_visual_placeholder(slide: Any, slide_data: Dict[str, Any], x: float, y: float, w: float, h: float, theme: Dict[str, Any]) -> None:
    colors = theme["colors"]
    visual_spec = slide_data.get("visual_spec") or {}
    primary = visual_spec.get("primary_visual") or {}
    vtype = primary.get("type") or slide_data.get("layout_type") or "visual"
    desc = primary.get("description") or visual_spec.get("overall_layout_description") or slide_data.get("audience_takeaway") or ""
    panel = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(x), Inches(y), Inches(w), Inches(h))
    panel.fill.solid()
    panel.fill.fore_color.rgb = rgbcolor(colors["panel_bg"])
    panel.line.color.rgb = rgbcolor(colors["accent_light"])
    pptx_add_textbox(slide, clean_text(vtype).replace("_", " ").title(), x + 0.35, y + 0.35, w - 0.7, 0.45, 15, colors["accent_dark"], theme["fonts"]["display"], True)
    if desc:
        pptx_add_textbox(slide, shorten(desc, 240), x + 0.35, y + 1.05, w - 0.7, h - 1.35, 13, colors["text_secondary"], theme["fonts"]["body"])


def add_evidence_line(slide: Any, slide_data: Dict[str, Any], x: float, y: float, w: float, theme: Dict[str, Any]) -> None:
    refs = collect_slide_evidence_refs(slide_data)
    if not refs:
        return
    text = "Evidence: " + ", ".join(refs[:6])
    pptx_add_textbox(slide, text, x, y, w, 0.28, 8.5, theme["colors"]["text_secondary"], theme["fonts"]["body"])


# ----------------------------- HTML builder -----------------------------


def build_html(deck: Dict[str, Any], theme: Dict[str, Any], asset_map: Dict[str, str], output_path: Path, density: str, ctx: BuildContext) -> Path:
    presentation = deck.get("presentation", {})
    slides = deck.get("slides", [])
    slides_html = "\n".join(slide_to_html(slide, idx, len(slides), theme, asset_map, density) for idx, slide in enumerate(slides, 1))
    css = build_html_css(theme, density)
    js = build_html_js()
    title = html_escape(presentation.get("title") or "Presentation")
    font_link = html_escape(theme["fonts"]["web_font_link"])

    template = Template(
        """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$title</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="$font_link">
    <style>
$css
    </style>
</head>
<body>
    <div class="deck-viewport" aria-label="Presentation viewport">
        <main class="deck-stage" id="deckStage" aria-label="Slide deck">
$slides_html
        </main>
    </div>
    <nav class="deck-controls" aria-label="Presentation controls">
        <button class="nav-button" id="prevBtn" aria-label="Previous slide">‹</button>
        <div class="progress-shell" aria-hidden="true"><div class="progress-fill" id="progressFill"></div></div>
        <span class="slide-counter" id="slideCounter">1 / 1</span>
        <button class="nav-button" id="nextBtn" aria-label="Next slide">›</button>
    </nav>
    <script>
$js
    </script>
</body>
</html>
"""
    )
    output = template.substitute(title=title, font_link=font_link, css=css, slides_html=slides_html, js=js)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding="utf-8")
    ctx.outputs["html"] = str(output_path)
    return output_path


def build_html_css(theme: Dict[str, Any], density: str) -> str:
    colors = theme["colors"]
    fonts = theme["fonts"]
    title_size = "86px" if density == "reading-first" else "104px"
    body_size = "28px" if density == "reading-first" else "32px"
    bullet_size = "27px" if density == "reading-first" else "31px"
    css = f"""
/* ===========================================
   CSS CUSTOM PROPERTIES: BRAND + FALLBACK THEME
   =========================================== */
:root {{
    --stage-bg: {colors['stage_bg']};
    --slide-bg: {colors['slide_bg']};
    --panel-bg: {colors['panel_bg']};
    --text-primary: {colors['text_primary']};
    --text-secondary: {colors['text_secondary']};
    --accent: {colors['accent']};
    --accent-light: {colors['accent_light']};
    --accent-dark: {colors['accent_dark']};
    --border: {colors['border']};
    --font-display: '{fonts['display']}', Manrope, Arial, sans-serif;
    --font-body: '{fonts['body']}', Manrope, Arial, sans-serif;
    --title-size: {title_size};
    --body-size: {body_size};
    --bullet-size: {bullet_size};
    --slide-padding: 96px;
    --content-gap: 42px;
    --radius-lg: 34px;
    --radius-md: 22px;
    --ease-out-expo: cubic-bezier(0.16, 1, 0.3, 1);
    --duration-normal: 0.7s;
}}

/* ===========================================
   BASE RESET
   =========================================== */
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
"""
    css += VIEWPORT_BASE_CSS
    css += r"""

/* ===========================================
   DECK-WIDE TYPOGRAPHY AND CHROME
   =========================================== */
body {
    font-family: var(--font-body);
    color: var(--text-primary);
}

.slide {
    padding: var(--slide-padding);
    font-family: var(--font-body);
    color: var(--text-primary);
    background:
        radial-gradient(circle at 92% 12%, color-mix(in srgb, var(--accent) 16%, transparent) 0, transparent 28%),
        linear-gradient(135deg, color-mix(in srgb, var(--slide-bg) 94%, var(--accent) 6%) 0%, var(--slide-bg) 100%);
}

.slide::before {
    content: "";
    position: absolute;
    inset: 34px;
    border: 1px solid color-mix(in srgb, var(--border) 70%, transparent);
    border-radius: 34px;
    pointer-events: none;
    opacity: 0.7;
}

.section-label {
    display: inline-flex;
    align-items: center;
    gap: 12px;
    padding: 10px 18px;
    border-radius: 999px;
    background: var(--accent-light);
    color: var(--accent-dark);
    font-size: 18px;
    line-height: 1;
    font-weight: 800;
    letter-spacing: 0.12em;
    text-transform: uppercase;
}

.section-label::before {
    content: "";
    width: 9px;
    height: 9px;
    border-radius: 50%;
    background: var(--accent);
}

.slide-title {
    font-family: var(--font-display);
    font-size: 58px;
    line-height: 0.98;
    letter-spacing: -0.04em;
    max-width: 1280px;
    margin-top: 32px;
}

.headline {
    font-size: 34px;
    line-height: 1.18;
    color: var(--accent-dark);
    max-width: 1050px;
    margin-top: 28px;
    font-weight: 750;
}

.body-text,
.bullet-list li,
.visual-description,
.note-text {
    font-size: var(--bullet-size);
    line-height: 1.28;
    color: var(--text-primary);
}

.bullet-list {
    display: grid;
    gap: 20px;
    list-style: none;
    margin-top: 34px;
}

.bullet-list li {
    position: relative;
    padding-left: 34px;
}

.bullet-list li::before {
    content: "";
    position: absolute;
    left: 0;
    top: 0.62em;
    width: 13px;
    height: 13px;
    border-radius: 4px;
    background: var(--accent);
    transform: rotate(45deg);
}

.evidence-row {
    position: absolute;
    left: 96px;
    right: 96px;
    bottom: 58px;
    font-size: 18px;
    line-height: 1.3;
    color: var(--text-secondary);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.slide-number {
    position: absolute;
    right: 96px;
    top: 74px;
    font-size: 20px;
    color: var(--text-secondary);
    font-weight: 700;
    letter-spacing: 0.08em;
}

/* ===========================================
   ANIMATION SYSTEM
   =========================================== */
.reveal {
    opacity: 0;
    transform: translateY(34px);
    transition:
        opacity var(--duration-normal) var(--ease-out-expo),
        transform var(--duration-normal) var(--ease-out-expo),
        filter var(--duration-normal) var(--ease-out-expo);
    filter: blur(6px);
}

.reveal-left {
    opacity: 0;
    transform: translateX(-48px);
    transition:
        opacity var(--duration-normal) var(--ease-out-expo),
        transform var(--duration-normal) var(--ease-out-expo),
        filter var(--duration-normal) var(--ease-out-expo);
    filter: blur(5px);
}

.reveal-scale {
    opacity: 0;
    transform: scale(0.94);
    transition:
        opacity var(--duration-normal) var(--ease-out-expo),
        transform var(--duration-normal) var(--ease-out-expo);
}

.slide.visible .reveal,
.slide.visible .reveal-left,
.slide.visible .reveal-scale {
    opacity: 1;
    transform: translate(0, 0) scale(1);
    filter: blur(0);
}

.slide.visible .delay-1 { transition-delay: 0.08s; }
.slide.visible .delay-2 { transition-delay: 0.16s; }
.slide.visible .delay-3 { transition-delay: 0.24s; }
.slide.visible .delay-4 { transition-delay: 0.32s; }
.slide.visible .delay-5 { transition-delay: 0.40s; }
.slide.visible .delay-6 { transition-delay: 0.48s; }

/* ===========================================
   LAYOUTS
   =========================================== */
.title-slide {
    display: grid;
    grid-template-columns: 1fr 520px;
    gap: 72px;
    align-items: end;
}

.title-slide .title-stack {
    position: relative;
    z-index: 2;
    padding-bottom: 86px;
}

.kicker {
    color: var(--accent-dark);
    font-size: 28px;
    font-weight: 800;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    margin-bottom: 28px;
}

.title-slide h1 {
    font-family: var(--font-display);
    font-size: var(--title-size);
    line-height: 0.92;
    letter-spacing: -0.065em;
    max-width: 1180px;
}

.title-slide .subtitle {
    margin-top: 38px;
    max-width: 980px;
    font-size: 34px;
    line-height: 1.24;
    color: var(--text-secondary);
}

.hero-orb {
    position: relative;
    width: 470px;
    height: 470px;
    border-radius: 46px;
    align-self: center;
    justify-self: center;
    background:
        linear-gradient(135deg, color-mix(in srgb, var(--accent) 92%, #fff 8%), var(--accent-dark)),
        var(--accent);
    box-shadow: 0 46px 110px color-mix(in srgb, var(--accent) 32%, transparent);
    overflow: hidden;
}

.hero-orb::before,
.hero-orb::after {
    content: "";
    position: absolute;
    border-radius: 50%;
    background: color-mix(in srgb, var(--slide-bg) 72%, transparent);
}
.hero-orb::before { width: 340px; height: 340px; right: -120px; top: -80px; }
.hero-orb::after { width: 210px; height: 210px; left: -62px; bottom: 38px; }

.split-layout {
    display: grid;
    grid-template-columns: 46% 1fr;
    gap: 74px;
    align-items: stretch;
}

.text-column {
    padding-top: 10px;
    min-width: 0;
}

.visual-panel {
    position: relative;
    min-width: 0;
    border-radius: var(--radius-lg);
    background: color-mix(in srgb, var(--panel-bg) 92%, var(--accent-light) 8%);
    border: 1px solid color-mix(in srgb, var(--border) 82%, transparent);
    padding: 46px;
    overflow: hidden;
    box-shadow: 0 28px 80px rgba(15, 23, 42, 0.12);
}

.visual-panel::after {
    content: "";
    position: absolute;
    width: 300px;
    height: 300px;
    border-radius: 50%;
    right: -128px;
    bottom: -140px;
    background: color-mix(in srgb, var(--accent) 20%, transparent);
}

.visual-type {
    position: relative;
    z-index: 2;
    display: inline-block;
    font-size: 18px;
    font-weight: 850;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--accent-dark);
    margin-bottom: 26px;
}

.visual-description {
    position: relative;
    z-index: 2;
    color: var(--text-primary);
    font-size: 31px;
    font-weight: 650;
    max-width: 680px;
}

.kpi-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 28px;
    margin-top: 72px;
}

.kpi-card {
    border-radius: var(--radius-lg);
    background: var(--panel-bg);
    border: 1px solid color-mix(in srgb, var(--border) 84%, transparent);
    padding: 38px 34px;
    min-height: 240px;
    box-shadow: 0 26px 70px rgba(15, 23, 42, 0.10);
}

.kpi-value {
    font-family: var(--font-display);
    font-size: 58px;
    line-height: 0.95;
    color: var(--accent-dark);
    letter-spacing: -0.04em;
}

.kpi-label {
    margin-top: 22px;
    font-size: 24px;
    line-height: 1.22;
    color: var(--text-secondary);
    font-weight: 650;
}

.process-flow {
    display: grid;
    grid-template-columns: repeat(var(--step-count, 4), minmax(0, 1fr));
    gap: 26px;
    margin-top: 86px;
    position: relative;
}

.step-card {
    position: relative;
    border-radius: var(--radius-lg);
    background: var(--panel-bg);
    border: 1px solid color-mix(in srgb, var(--border) 84%, transparent);
    padding: 34px 30px 42px;
    min-height: 260px;
    box-shadow: 0 24px 70px rgba(15, 23, 42, 0.10);
}

.step-number {
    width: 54px;
    height: 54px;
    border-radius: 50%;
    display: grid;
    place-items: center;
    background: var(--accent);
    color: var(--slide-bg);
    font-weight: 900;
    font-size: 23px;
    margin-bottom: 34px;
}

.step-text {
    font-size: 28px;
    line-height: 1.18;
    font-weight: 750;
}

.comparison-grid {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 28px;
    margin-top: 64px;
}

.comparison-card {
    border-radius: var(--radius-lg);
    background: var(--panel-bg);
    border: 1px solid color-mix(in srgb, var(--border) 84%, transparent);
    padding: 36px;
    min-height: 180px;
    box-shadow: 0 24px 70px rgba(15, 23, 42, 0.10);
}

.comparison-card h3 {
    font-family: var(--font-display);
    font-size: 28px;
    margin-bottom: 16px;
    color: var(--accent-dark);
}

.comparison-card p {
    font-size: 25px;
    line-height: 1.26;
    color: var(--text-primary);
}

.quote-card {
    display: grid;
    place-items: center;
    text-align: center;
}

.quote-card blockquote {
    max-width: 1260px;
    font-family: var(--font-display);
    font-size: 72px;
    line-height: 1.02;
    letter-spacing: -0.045em;
    color: var(--text-primary);
}

.quote-card cite {
    margin-top: 34px;
    font-size: 26px;
    color: var(--text-secondary);
    font-style: normal;
}

.asset-image {
    position: relative;
    z-index: 2;
    max-width: 100%;
    max-height: 580px;
    object-fit: contain;
    border-radius: 22px;
    box-shadow: 0 24px 70px rgba(15, 23, 42, 0.16);
}

/* ===========================================
   NAVIGATION UI OUTSIDE SLIDE STAGE
   =========================================== */
.deck-controls {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 10px 14px;
    border-radius: 999px;
    background: rgba(15, 23, 42, 0.72);
    backdrop-filter: blur(12px);
    color: #fff;
    font-family: var(--font-body);
}

.nav-button {
    border: 0;
    border-radius: 999px;
    width: 34px;
    height: 34px;
    cursor: pointer;
    background: rgba(255, 255, 255, 0.12);
    color: #fff;
    font-size: 24px;
    line-height: 1;
}

.nav-button:hover { background: rgba(255, 255, 255, 0.22); }

.progress-shell {
    width: 120px;
    height: 5px;
    border-radius: 999px;
    background: rgba(255, 255, 255, 0.18);
    overflow: hidden;
}

.progress-fill {
    width: 0%;
    height: 100%;
    background: var(--accent);
    transition: width 260ms ease;
}

.slide-counter {
    min-width: 54px;
    font-size: 13px;
    font-weight: 700;
    letter-spacing: 0.08em;
}
"""
    return css


def slide_to_html(slide: Dict[str, Any], idx: int, total: int, theme: Dict[str, Any], asset_map: Dict[str, str], density: str) -> str:
    layout = clean_text(slide.get("layout_type") or infer_layout_type(slide))
    title = slide.get("title") or f"Slide {idx}"
    section = slide.get("section") or ""
    content = slide.get("content") or {}
    headline = content.get("headline") or slide.get("audience_takeaway") or slide.get("purpose") or ""
    bullets = [clean_text(b) for b in as_list(content.get("bullets")) if clean_text(b)]
    evidence = collect_slide_evidence_refs(slide)
    slide_classes = f"slide layout-{slugify(layout)}"
    active = " active visible" if idx == 1 else ""
    slide_number = f"{idx:02d} / {total:02d}"

    if idx == 1 or layout == "title_or_opening":
        return render_html_title_slide(slide, idx, total, active)
    if layout == "metric_dashboard":
        body = render_html_metric_slide(slide, idx, total)
    elif layout in {"full_process_flow", "timeline", "roadmap"}:
        body = render_html_process_slide(slide, idx, total)
    elif layout in {"comparison_grid", "data_table"}:
        body = render_html_comparison_slide(slide, idx, total)
    elif layout == "quote_card":
        body = render_html_quote_slide(slide, idx, total)
    else:
        body = render_html_default_slide(slide, idx, total, asset_map)

    evidence_html = f'<div class="evidence-row">Evidence: {html_escape(", ".join(evidence[:8]))}</div>' if evidence else ""
    return f"""            <section class=\"{slide_classes}{active}\" data-slide-number=\"{idx}\">
                <div class=\"slide-number\">{html_escape(slide_number)}</div>
{body}
{evidence_html}
            </section>"""


def render_html_title_slide(slide: Dict[str, Any], idx: int, total: int, active: str) -> str:
    content = slide.get("content") or {}
    title = slide.get("title") or "Presentation"
    subtitle = slide.get("subtitle") or content.get("headline") or slide.get("audience_takeaway") or ""
    section = slide.get("section") or ""
    evidence = collect_slide_evidence_refs(slide)
    evidence_html = f'<div class="evidence-row">Evidence: {html_escape(", ".join(evidence[:8]))}</div>' if evidence else ""
    return f"""            <section class=\"slide title-slide{active}\" data-slide-number=\"{idx}\">
                <div class=\"slide-number\">{idx:02d} / {total:02d}</div>
                <div class=\"title-stack\">
                    <div class=\"kicker reveal-left delay-1\">{html_escape(section or "Presentation")}</div>
                    <h1 class=\"reveal-left delay-2\">{html_escape(title)}</h1>
                    <p class=\"subtitle reveal-left delay-3\">{html_escape(subtitle)}</p>
                </div>
                <div class=\"hero-orb reveal-scale delay-3\" aria-hidden=\"true\"></div>
{evidence_html}
            </section>"""


def render_html_default_slide(slide: Dict[str, Any], idx: int, total: int, asset_map: Dict[str, str]) -> str:
    content = slide.get("content") or {}
    title = slide.get("title") or f"Slide {idx}"
    section = slide.get("section") or ""
    headline = content.get("headline") or slide.get("audience_takeaway") or ""
    bullets = [clean_text(b) for b in as_list(content.get("bullets")) if clean_text(b)]
    visual = slide.get("visual_spec") or {}
    primary = visual.get("primary_visual") or {}
    visual_type = primary.get("type") or slide.get("layout_type") or "visual"
    description = primary.get("description") or visual.get("overall_layout_description") or slide.get("purpose") or ""
    asset_html = render_first_slide_asset(slide, asset_map)
    if asset_html:
        visual_body = asset_html
    else:
        visual_body = f"""<div class=\"visual-type\">{html_escape(clean_text(visual_type).replace('_', ' '))}</div>
                    <p class=\"visual-description\">{html_escape(description)}</p>"""
    bullets_html = "\n".join(f'<li class="reveal-left delay-{min(i+3, 6)}">{html_escape(b)}</li>' for i, b in enumerate(bullets[:6]))
    return f"""                <div class=\"split-layout\">
                    <div class=\"text-column\">
                        <div class=\"section-label reveal-left delay-1\">{html_escape(section)}</div>
                        <h2 class=\"slide-title reveal-left delay-2\">{html_escape(title)}</h2>
                        <p class=\"headline reveal-left delay-3\">{html_escape(headline)}</p>
                        <ul class=\"bullet-list\">
{bullets_html}
                        </ul>
                    </div>
                    <aside class=\"visual-panel reveal-scale delay-3\">
                    {visual_body}
                    </aside>
                </div>"""


def render_html_metric_slide(slide: Dict[str, Any], idx: int, total: int) -> str:
    content = slide.get("content") or {}
    title = slide.get("title") or f"Slide {idx}"
    section = slide.get("section") or ""
    headline = content.get("headline") or slide.get("audience_takeaway") or ""
    stats = as_list(content.get("key_stats"))
    if not stats:
        stats = [{"label": f"Point {i+1}", "value": b} for i, b in enumerate(as_list(content.get("bullets"))[:4])]
    cards = []
    for i, stat in enumerate(stats[:4]):
        if isinstance(stat, dict):
            value = stat.get("value") or stat.get("label") or "—"
            label = stat.get("label") or stat.get("source") or ""
        else:
            value, label = stat, ""
        cards.append(
            f"""<article class=\"kpi-card reveal-scale delay-{min(i+2, 6)}\">
                            <div class=\"kpi-value\">{html_escape(value)}</div>
                            <div class=\"kpi-label\">{html_escape(label)}</div>
                        </article>"""
        )
    cards_html = "\n".join(cards)
    return f"""                <div class=\"section-label reveal-left delay-1\">{html_escape(section)}</div>
                <h2 class=\"slide-title reveal-left delay-2\">{html_escape(title)}</h2>
                <p class=\"headline reveal-left delay-3\">{html_escape(headline)}</p>
                <div class=\"kpi-grid\">
{cards_html}
                </div>"""


def render_html_process_slide(slide: Dict[str, Any], idx: int, total: int) -> str:
    content = slide.get("content") or {}
    title = slide.get("title") or f"Slide {idx}"
    section = slide.get("section") or ""
    headline = content.get("headline") or slide.get("audience_takeaway") or ""
    steps = extract_visual_steps(slide) or [clean_text(b) for b in as_list(content.get("bullets")) if clean_text(b)]
    steps = steps[:6] or ["Step 1", "Step 2", "Step 3"]
    cards = []
    for i, step in enumerate(steps):
        cards.append(
            f"""<article class=\"step-card reveal-scale delay-{min(i+2, 6)}\">
                            <div class=\"step-number\">{i + 1}</div>
                            <div class=\"step-text\">{html_escape(step)}</div>
                        </article>"""
        )
    return f"""                <div class=\"section-label reveal-left delay-1\">{html_escape(section)}</div>
                <h2 class=\"slide-title reveal-left delay-2\">{html_escape(title)}</h2>
                <p class=\"headline reveal-left delay-3\">{html_escape(headline)}</p>
                <div class=\"process-flow\" style=\"--step-count: {len(steps)}\">
{chr(10).join(cards)}
                </div>"""


def render_html_comparison_slide(slide: Dict[str, Any], idx: int, total: int) -> str:
    content = slide.get("content") or {}
    title = slide.get("title") or f"Slide {idx}"
    section = slide.get("section") or ""
    headline = content.get("headline") or slide.get("audience_takeaway") or ""
    items = extract_visual_steps(slide) or [clean_text(b) for b in as_list(content.get("bullets")) if clean_text(b)]
    if not items:
        items = ["Comparison point 1", "Comparison point 2"]
    cards = []
    for i, item in enumerate(items[:6]):
        if isinstance(item, str) and ":" in item[:80]:
            heading, body = item.split(":", 1)
        else:
            heading, body = f"Point {i + 1}", item
        cards.append(
            f"""<article class=\"comparison-card reveal-scale delay-{min(i+2, 6)}\">
                            <h3>{html_escape(heading)}</h3>
                            <p>{html_escape(body)}</p>
                        </article>"""
        )
    return f"""                <div class=\"section-label reveal-left delay-1\">{html_escape(section)}</div>
                <h2 class=\"slide-title reveal-left delay-2\">{html_escape(title)}</h2>
                <p class=\"headline reveal-left delay-3\">{html_escape(headline)}</p>
                <div class=\"comparison-grid\">
{chr(10).join(cards)}
                </div>"""


def render_html_quote_slide(slide: Dict[str, Any], idx: int, total: int) -> str:
    content = slide.get("content") or {}
    quote = content.get("body_text") or content.get("headline") or slide.get("audience_takeaway") or slide.get("title")
    refs = collect_slide_evidence_refs(slide)
    cite = ", ".join(refs[:2]) if refs else slide.get("section", "")
    return f"""                <div class=\"quote-card\">
                    <blockquote class=\"reveal-scale delay-2\">“{html_escape(quote)}”</blockquote>
                    <cite class=\"reveal delay-3\">{html_escape(cite)}</cite>
                </div>"""


def extract_visual_steps(slide: Dict[str, Any]) -> List[str]:
    visual = slide.get("visual_spec") or {}
    primary = visual.get("primary_visual") or {}
    raw = primary.get("steps_or_data") or primary.get("steps") or primary.get("data") or []
    result: List[str] = []
    for item in as_list(raw):
        if isinstance(item, dict):
            text = item.get("label") or item.get("title") or item.get("name") or item.get("step") or item.get("value") or json.dumps(item, ensure_ascii=False)
        else:
            text = item
        text = clean_text(text)
        if text:
            result.append(text)
    return result


def collect_slide_asset_refs(slide: Dict[str, Any]) -> List[str]:
    refs: List[str] = []
    refs.extend(clean_text(x) for x in as_list(slide.get("visual_assets_references")))
    visual = slide.get("visual_spec") or {}
    refs.extend(clean_text(x) for x in as_list(visual.get("assets_to_use")))
    for sv in as_list(visual.get("supporting_visuals")):
        if isinstance(sv, dict):
            refs.append(clean_text(sv.get("value_or_content") or sv.get("asset") or ""))
    return [r for r in refs if r]


def render_first_slide_asset(slide: Dict[str, Any], asset_map: Dict[str, str]) -> str:
    for ref in collect_slide_asset_refs(slide):
        uri = find_asset_uri(ref, asset_map)
        if uri:
            return f'<img class="asset-image" src="{html_escape(uri)}" alt="{html_escape(ref)}">'
    return ""


def build_html_js() -> str:
    return r"""
/* ===========================================
   SLIDE PRESENTATION CONTROLLER
   =========================================== */
class SlidePresentation {
    constructor() {
        this.slides = Array.from(document.querySelectorAll('.slide'));
        this.currentSlide = 0;
        this.stage = document.getElementById('deckStage');
        this.progressFill = document.getElementById('progressFill');
        this.slideCounter = document.getElementById('slideCounter');
        this.prevBtn = document.getElementById('prevBtn');
        this.nextBtn = document.getElementById('nextBtn');
        this.wheelLock = false;
        this.touchStartX = 0;
        this.touchStartY = 0;
        this.setupStageScale();
        this.setupKeyboardNav();
        this.setupTouchNav();
        this.setupWheelNav();
        this.setupButtons();
        this.showSlide(0);
    }

    setupStageScale() {
        const scale = () => {
            const factor = Math.min(window.innerWidth / 1920, window.innerHeight / 1080);
            const x = (window.innerWidth - 1920 * factor) / 2;
            const y = (window.innerHeight - 1080 * factor) / 2;
            this.stage.style.transform = `translate(${x}px, ${y}px) scale(${factor})`;
        };
        scale();
        window.addEventListener('resize', scale);
    }

    setupKeyboardNav() {
        document.addEventListener('keydown', (e) => {
            if (['ArrowRight', ' ', 'PageDown', 'Enter'].includes(e.key)) {
                e.preventDefault();
                this.next();
            } else if (['ArrowLeft', 'PageUp', 'Backspace'].includes(e.key)) {
                e.preventDefault();
                this.prev();
            } else if (e.key === 'Home') {
                e.preventDefault();
                this.showSlide(0);
            } else if (e.key === 'End') {
                e.preventDefault();
                this.showSlide(this.slides.length - 1);
            }
        });
    }

    setupTouchNav() {
        document.addEventListener('touchstart', (e) => {
            const t = e.changedTouches[0];
            this.touchStartX = t.clientX;
            this.touchStartY = t.clientY;
        }, { passive: true });

        document.addEventListener('touchend', (e) => {
            const t = e.changedTouches[0];
            const dx = t.clientX - this.touchStartX;
            const dy = t.clientY - this.touchStartY;
            if (Math.abs(dx) > 60 && Math.abs(dx) > Math.abs(dy)) {
                if (dx < 0) this.next(); else this.prev();
            }
        }, { passive: true });
    }

    setupWheelNav() {
        document.addEventListener('wheel', (e) => {
            if (this.wheelLock || Math.abs(e.deltaY) < 24) return;
            this.wheelLock = true;
            if (e.deltaY > 0) this.next(); else this.prev();
            setTimeout(() => { this.wheelLock = false; }, 520);
        }, { passive: true });
    }

    setupButtons() {
        this.prevBtn.addEventListener('click', () => this.prev());
        this.nextBtn.addEventListener('click', () => this.next());
    }

    showSlide(index) {
        this.currentSlide = Math.max(0, Math.min(index, this.slides.length - 1));
        this.slides.forEach((slide, i) => {
            const active = i === this.currentSlide;
            slide.classList.toggle('active', active);
            slide.classList.toggle('visible', active);
            slide.setAttribute('aria-hidden', active ? 'false' : 'true');
        });
        const total = Math.max(this.slides.length, 1);
        const current = this.currentSlide + 1;
        this.slideCounter.textContent = `${current} / ${total}`;
        this.progressFill.style.width = `${(current / total) * 100}%`;
        this.prevBtn.disabled = this.currentSlide === 0;
        this.nextBtn.disabled = this.currentSlide === this.slides.length - 1;
    }

    next() { this.showSlide(this.currentSlide + 1); }
    prev() { this.showSlide(this.currentSlide - 1); }
}

window.presentation = new SlidePresentation();
"""


# ----------------------------- HTML validation / PDF -----------------------------


def validate_html_file(html_path: Path, expected_slide_count: int, theme: Dict[str, Any], ctx: BuildContext) -> Dict[str, Any]:
    text = html_path.read_text(encoding="utf-8")
    checks = []

    def add(name: str, status: str, notes: str = "") -> None:
        checks.append({"check": name, "status": status, "notes": notes})
        if status == "error":
            ctx.error(f"HTML: {name}: {notes}")
        elif status == "warning":
            ctx.warn(f"HTML: {name}: {notes}")

    if BeautifulSoup is not None:
        soup = BeautifulSoup(text, "html.parser")
        slides = soup.select(".slide")
        add(".deck-viewport exists", "pass" if soup.select_one(".deck-viewport") else "error")
        add(".deck-stage exists", "pass" if soup.select_one(".deck-stage") else "error")
        add(".slide count", "pass" if len(slides) == expected_slide_count else "warning", f"Expected {expected_slide_count}, found {len(slides)}")
        add("First slide active", "pass" if slides and "active" in slides[0].get("class", []) else "warning")
    else:
        add("beautifulsoup4 available", "warning", "Install beautifulsoup4 for deeper HTML validation")
        slide_count = 0
        for class_attr in re.findall(r'class="([^"]*)"', text):
            tokens = re.split(r"\s+", class_attr.strip())
            if "slide" in tokens:
                slide_count += 1
        add(".slide count", "pass" if slide_count == expected_slide_count else "warning", f"Expected {expected_slide_count}, found {slide_count}")

    add("Fixed stage CSS width", "pass" if "width: 1920px" in text else "error")
    add("Fixed stage CSS height", "pass" if "height: 1080px" in text else "error")
    add("Uses active/visible switching", "pass" if ".slide.active" in text and ".slide.visible" in text else "error")
    slide_switching_display_none = bool(re.search(r"\.slide[^{}]*\{[^{}]*display\s*:\s*none", text, flags=re.IGNORECASE | re.DOTALL))
    add("Avoids display:none slide switching", "pass" if not slide_switching_display_none else "warning", "display:none found on .slide rule" if slide_switching_display_none else "")
    add("Reduced motion support", "pass" if "prefers-reduced-motion" in text else "warning")
    add("Embedded asset support", "pass" if "data:image/" in text or "assets_to_use" not in text else "warning")
    add("Brand accent token used", "pass" if theme["colors"]["accent"] in text else "warning")

    result = {"html_path": str(html_path), "checks": checks}
    ctx.html_validation = result
    return result


def visual_validate_with_playwright(html_path: Path, output_dir: Path, ctx: BuildContext) -> Dict[str, Any]:
    try:
        from playwright.sync_api import sync_playwright  # type: ignore
    except Exception as exc:  # noqa: BLE001
        msg = f"Playwright unavailable: {exc}. Install with: python -m pip install playwright && python -m playwright install chromium"
        ctx.warn(msg)
        return {"status": "skipped", "reason": msg}

    console_errors: List[str] = []
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch()
            page = browser.new_page(viewport={"width": STAGE_W, "height": STAGE_H}, device_scale_factor=1)
            page.on("console", lambda msg: console_errors.append(msg.text) if msg.type == "error" else None)
            page.goto(html_path.resolve().as_uri(), wait_until="networkidle")
            metrics = page.evaluate(
                """() => Array.from(document.querySelectorAll('.slide')).map((s, i) => ({
                    slide: i + 1,
                    width: s.offsetWidth,
                    height: s.offsetHeight,
                    scrollWidth: s.scrollWidth,
                    scrollHeight: s.scrollHeight,
                    textLength: s.innerText.length,
                    overflowRisk: s.scrollWidth > s.clientWidth + 2 || s.scrollHeight > s.clientHeight + 2
                }))"""
            )
            screenshot_dir = output_dir / "html_screenshots"
            screenshot_dir.mkdir(parents=True, exist_ok=True)
            if metrics:
                page.screenshot(path=str(screenshot_dir / "slide_001.png"), full_page=False)
            browser.close()
        result = {"status": "ok", "console_errors": console_errors, "slide_metrics": metrics, "screenshot_dir": str(screenshot_dir)}
        if console_errors:
            ctx.warn(f"HTML console errors detected: {len(console_errors)}")
        return result
    except Exception as exc:  # noqa: BLE001
        ctx.warn(f"Playwright visual validation failed: {exc}")
        return {"status": "error", "error": str(exc), "traceback": traceback.format_exc(limit=4)}


def export_html_to_pdf(html_path: Path, pdf_path: Path, ctx: BuildContext) -> Optional[Path]:
    try:
        from playwright.sync_api import sync_playwright  # type: ignore
    except Exception as exc:  # noqa: BLE001
        ctx.error(f"Cannot export PDF: Playwright unavailable: {exc}")
        return None
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch()
            page = browser.new_page(viewport={"width": STAGE_W, "height": STAGE_H}, device_scale_factor=1)
            page.goto(html_path.resolve().as_uri(), wait_until="networkidle")
            page.emulate_media(media="print")
            pdf_path.parent.mkdir(parents=True, exist_ok=True)
            page.pdf(path=str(pdf_path), width="1920px", height="1080px", print_background=True, prefer_css_page_size=True)
            browser.close()
        ctx.outputs["html_pdf"] = str(pdf_path)
        return pdf_path
    except Exception as exc:  # noqa: BLE001
        ctx.error(f"HTML to PDF export failed: {exc}")
        return None


# ----------------------------- reporting -----------------------------


def render_validation_report_md(report: Dict[str, Any]) -> str:
    lines = [
        "# Step 4 Builder / Validator Report",
        "",
        f"Generated: {report.get('generated_at')}",
        "",
        "## Outputs",
        "",
    ]
    outputs = report.get("outputs") or {}
    if outputs:
        for key, value in outputs.items():
            lines.append(f"- **{key}:** `{value}`")
    else:
        lines.append("No output files generated.")

    lines.extend(["", "## Errors", ""])
    errors = report.get("errors") or []
    lines.extend([f"- {e}" for e in errors] if errors else ["None"])

    lines.extend(["", "## Warnings", ""])
    warnings = report.get("warnings") or []
    lines.extend([f"- {w}" for w in warnings] if warnings else ["None"])

    lines.extend(["", "## Theme", ""])
    theme = report.get("theme") or {}
    colors = (theme.get("colors") or {}) if isinstance(theme, dict) else {}
    fonts = (theme.get("fonts") or {}) if isinstance(theme, dict) else {}
    lines.append(f"- **Accent:** `{colors.get('accent')}`")
    lines.append(f"- **Slide background:** `{colors.get('slide_bg')}`")
    lines.append(f"- **Text:** `{colors.get('text_primary')}`")
    lines.append(f"- **Display font:** `{fonts.get('display')}`")
    lines.append(f"- **Body font:** `{fonts.get('body')}`")
    if theme.get("fallbacks_used"):
        lines.append("- **Fallbacks used:** " + "; ".join(theme.get("fallbacks_used")))

    lines.extend(["", "## Validation Checks", ""])
    checks = ((report.get("validation") or {}).get("checks") or [])
    lines.append("| Check | Status | Notes |")
    lines.append("|---|---|---|")
    for check in checks:
        lines.append(f"| {check.get('check')} | {check.get('status')} | {str(check.get('notes') or '').replace('|', '/')} |")

    html_validation = report.get("html_validation") or {}
    if html_validation:
        lines.extend(["", "## HTML Validation", "", "| Check | Status | Notes |", "|---|---|---|"])
        for check in html_validation.get("checks", []):
            lines.append(f"| {check.get('check')} | {check.get('status')} | {str(check.get('notes') or '').replace('|', '/')} |")

    visual_validation = report.get("visual_validation")
    if visual_validation:
        lines.extend(["", "## Visual Validation", "", f"- **Status:** {visual_validation.get('status')}"])
        if visual_validation.get("console_errors"):
            lines.append(f"- **Console errors:** {len(visual_validation.get('console_errors'))}")
        if visual_validation.get("screenshot_dir"):
            lines.append(f"- **Screenshot dir:** `{visual_validation.get('screenshot_dir')}`")

    lines.extend(["", "## Package Import Warnings", ""])
    if IMPORT_WARNINGS:
        for pkg, warning in sorted(IMPORT_WARNINGS.items()):
            lines.append(f"- `{pkg}`: {warning}")
    else:
        lines.append("None")
    return "\n".join(lines) + "\n"


# ----------------------------- CLI -----------------------------


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build/validate PPTX and standalone HTML decks from Final_Slide_Content.json.")
    parser.add_argument("--input", "-i", required=True, help="Path to Final_Slide_Content.json")
    parser.add_argument("--brand", "-b", default=None, help="Path to brand_style_summary.json")
    parser.add_argument("--output", "-o", default=None, help="Output folder")
    parser.add_argument("--assets", default=None, help="Path to asset_manifest.json")
    parser.add_argument("--asset-root", default=None, help="Folder containing source image/assets to embed in HTML")
    parser.add_argument("--pptx", action="store_true", help="Generate updated_presentation.pptx")
    parser.add_argument("--html", action="store_true", help="Generate standalone presentation.html")
    parser.add_argument("--export-html-pdf", action="store_true", help="Export HTML deck to presentation.pdf using Playwright")
    parser.add_argument("--density", choices=["speaker-led", "reading-first"], default="speaker-led", help="HTML content density mode")
    parser.add_argument("--open-html", action="store_true", help="Open generated HTML in default browser")
    parser.add_argument("--validate-visual", action="store_true", help="Run Playwright visual validation on generated HTML")
    parser.add_argument("--title", default=None, help="Override presentation title")
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    ctx = BuildContext()

    input_path = Path(args.input).expanduser().resolve()
    if not input_path.exists():
        print(f"ERROR: input JSON not found: {input_path}", file=sys.stderr)
        return 2
    output_dir = Path(args.output).expanduser().resolve() if args.output else default_output_dir(input_path).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    # If neither output flag is set, generate both by default.
    generate_pptx = args.pptx or (not args.pptx and not args.html)
    generate_html = args.html or (not args.pptx and not args.html)

    try:
        raw = load_json(input_path)
        if not isinstance(raw, dict):
            raise ValueError("Input JSON must be an object")
        deck = normalize_final_json(raw)
        if args.title:
            deck.setdefault("presentation", {})["title"] = args.title
    except Exception as exc:  # noqa: BLE001
        print(f"ERROR: failed to load input JSON: {exc}", file=sys.stderr)
        return 2

    brand: Dict[str, Any] = {}
    if args.brand:
        brand_path = Path(args.brand).expanduser().resolve()
        if brand_path.exists():
            try:
                brand = load_json(brand_path)
                if not isinstance(brand, dict):
                    ctx.warn("brand_style_summary.json did not contain a JSON object; using fallback theme")
                    brand = {}
            except Exception as exc:  # noqa: BLE001
                ctx.warn(f"Could not load brand file {brand_path}: {exc}")
        else:
            ctx.warn(f"Brand file not found: {brand_path}; using fallback theme")
    else:
        ctx.warn("No brand file supplied; using fallback theme")

    validation = validate_final_content(deck, ctx)
    theme = resolve_brand_theme(brand, ctx)

    asset_manifest = None
    if args.assets:
        asset_path = Path(args.assets).expanduser().resolve()
        if asset_path.exists():
            try:
                asset_manifest = load_json(asset_path)
            except Exception as exc:  # noqa: BLE001
                ctx.warn(f"Could not load asset manifest {asset_path}: {exc}")
        else:
            ctx.warn(f"Asset manifest not found: {asset_path}")
    asset_root = Path(args.asset_root).expanduser().resolve() if args.asset_root else None
    asset_map = build_asset_map(asset_manifest, asset_root, ctx) if generate_html else {}

    pptx_path = output_dir / "updated_presentation.pptx"
    html_path = output_dir / "presentation.html"
    pdf_path = output_dir / "presentation.pdf"
    visual_validation = None

    if generate_pptx:
        try:
            build_pptx(deck, theme, pptx_path, ctx)
        except Exception as exc:  # noqa: BLE001
            ctx.error(f"PPTX generation failed: {exc}")
            ctx.outputs["pptx_error_traceback"] = traceback.format_exc(limit=5)

    if generate_html:
        try:
            build_html(deck, theme, asset_map, html_path, args.density, ctx)
            html_validation = validate_html_file(html_path, len(deck.get("slides", [])), theme, ctx)
            if args.validate_visual:
                visual_validation = visual_validate_with_playwright(html_path, output_dir, ctx)
            if args.export_html_pdf:
                export_html_to_pdf(html_path, pdf_path, ctx)
            if args.open_html:
                webbrowser.open(html_path.as_uri())
        except Exception as exc:  # noqa: BLE001
            ctx.error(f"HTML generation failed: {exc}")
            ctx.outputs["html_error_traceback"] = traceback.format_exc(limit=5)

    report = {
        "generated_at": now_iso(),
        "input": str(input_path),
        "output_dir": str(output_dir),
        "validation": validation,
        "theme": theme,
        "outputs": ctx.outputs,
        "errors": ctx.errors,
        "warnings": ctx.warnings,
        "infos": ctx.infos,
        "html_validation": ctx.html_validation,
        "visual_validation": visual_validation,
        "import_warnings": IMPORT_WARNINGS,
    }
    write_json(output_dir / "validation_report.json", report)
    write_text(output_dir / "validation_report.md", render_validation_report_md(report))

    print(f"Done. Outputs written to: {output_dir}")
    if ctx.errors:
        print(f"Completed with {len(ctx.errors)} error(s). See validation_report.md", file=sys.stderr)
        # Do not fail hard if optional PPTX/PDF dependency is missing; validation report captures it.
        return 1 if not ctx.outputs else 0
    if ctx.warnings:
        print(f"Completed with {len(ctx.warnings)} warning(s). See validation_report.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
